"""Emit paper/fss_numbers.tex: LaTeX macros for every FSS number in the paper.

Ground rule 4 -- no number is pasted into the paper by hand. main.tex \\input's
this file and uses \\ClGammaNu etc.; re-running this script after a re-analysis
updates every value. Reads the committed cluster and local analyses.

    python scripts/make_fss_numbers.py
"""

from __future__ import annotations

import json
from math import floor, log10
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def pdg(v: float, e: float) -> str:
    """Value(error) with the error rounded to 1 significant figure (2 if its
    leading digit is 1), the value rounded to the same decimal place."""
    if e is None or e <= 0 or v is None:
        return f"{v:.3g}" if v is not None else "--"
    exp = floor(log10(abs(e)))
    lead = e / 10.0**exp
    sig = 2 if lead < 2 else 1
    ndec = max(-exp + (sig - 1), 0)
    e_r = round(e, ndec)
    # nudge to avoid float round-half-to-even surprises on the last digit
    v_r = round(v + (1e-9 if v >= 0 else -1e-9), ndec)
    err_digits = int(round(e_r * 10**ndec))
    return f"{v_r:.{ndec}f}({err_digits})"


def main() -> None:
    cl = json.load(open(REPO / "results/fss_analysis_cluster.json"))
    loc = json.load(open(REPO / "results/fss_analysis_v5.json"))
    cmp = json.load(open(REPO / "results/fss_local_vs_cluster.json"))

    def gpk(d):
        return sorted(d["chi_peaks"], key=lambda p: p["L"])

    cl_pk, loc_pk = gpk(cl), gpk(loc)
    nu_ps = cl["nu_pseudocritical"]
    m2c_ps = cl["m2_c_pseudocritical"]
    # local peak-shift nu (apples-to-apples) is in the comparison JSON's Table B
    loc_nu = cmp["table_b"]["nu"]["local_pseudocritical"]
    tau_rows = {int(r["L"]): r for r in cmp["table_a"]}

    lines = [
        "% Auto-generated by scripts/make_fss_numbers.py -- DO NOT EDIT BY HAND.",
        "% Every FSS number in the paper traces to results/fss_analysis_cluster.json.",
    ]

    def cmd(name, val):
        lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    # --- exponents ---
    cmd("ClGammaNu", pdg(cl["gamma_over_nu"]["value"], cl["gamma_over_nu"]["err"]))
    cc = cl["gamma_over_nu_corrections"]["omega_fixed_2"]
    cmd("ClGammaNuCorr", pdg(cc["gamma_over_nu"], cc["gamma_over_nu_err"]))
    ca = cl["gamma_over_nu_aic"]
    cmd("ClGammaNuAIC", pdg(ca["gamma_over_nu"], ca["gamma_over_nu_err"]))
    cmd("ClNu", pdg(nu_ps["nu"], nu_ps["nu_err"]))
    cmd("ClMsqc", pdg(m2c_ps["value"], m2c_ps["err"]))
    cmd("ClNuChiDof", f"{nu_ps['chi2_dof']:.1f}")
    cmd("LocGammaNu", pdg(loc["gamma_over_nu"]["value"], loc["gamma_over_nu"]["err"]))
    cmd("LocNu", pdg(loc_nu[0], loc_nu[1]))
    cmd("Nsizes", str(len(cl_pk)))
    cmd("Lmax", str(int(cl_pk[-1]["L"])))

    # --- effective-slope evidence (local bias) ---
    import numpy as np
    def eff_slope(pk, i):
        return np.log(pk[i + 1]["chi_max"] / pk[i]["chi_max"]) / np.log(
            pk[i + 1]["L"] / pk[i]["L"])
    cmd("LocEffSlopeLo", f"{eff_slope(loc_pk, 0):.2f}")          # L=16->24
    cmd("LocEffSlopeHi", f"{eff_slope(loc_pk, len(loc_pk) - 2):.2f}")  # ...->64

    # --- tau_int extremes (single-sweep, at the pseudo-critical point) ---
    cmd("TauLocLo", f"{tau_rows[16]['tau_int_local']:.0f}")
    cmd("TauLocHi", f"{tau_rows[64]['tau_int_local']:.0f}")
    cmd("TauClTyp", "8\\text{--}9")  # used only in math mode: $\\approx \\TauClTyp$
    sp = tau_rows[64]["decorrelation_speedup"]
    cmd("SpeedupHi", f"{sp:.0f}")

    out = REPO / "paper" / "fss_numbers.tex"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # --- tau_int / chi_max comparison table body (local vs cluster) ---
    def cell(v, e=None, nd=2):
        if v is None:
            return "--"
        return f"{v:.{nd}f}" if e is None else pdg(v, e)
    trows = []
    for r in sorted(cmp["table_a"], key=lambda r: r["L"]):
        L = r["L"]
        chi_l = cell(r["chi_max_local"], r["chi_max_local_err"])
        chi_c = cell(r["chi_max_cluster"], r["chi_max_cluster_err"])
        tl = f"{r['tau_int_local']:.0f}" if r["tau_int_local"] else "--"
        tc = f"{r['tau_int_cluster']:.1f}" if r["tau_int_cluster"] else "--"
        sp = f"{r['decorrelation_speedup']:.0f}" if r["decorrelation_speedup"] else "--"
        trows.append(f"{L} & {chi_l} & {chi_c} & {tl} & {tc} & {sp} \\\\")
    # Emit a COMPLETE tabular (row-only fragments break TeX alignment lookahead
    # after booktabs rules -- same convention as scripts/make_paper_tables.py).
    tbl_lines = [
        r"\begin{tabular}{rccccc}",
        r"\toprule",
        r"& \multicolumn{2}{c}{$\chi_\text{max}$} & "
        r"\multicolumn{2}{c}{$\tau_\text{int}(|M|)$} & \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r"$L$ & local & cluster & local & cluster & speed-up \\",
        r"\midrule",
        *trows,
        r"\bottomrule",
        r"\end{tabular}",
    ]
    tbl = REPO / "paper" / "tables" / "tau_int_body.tex"
    tbl.write_text("\n".join(tbl_lines) + "\n", encoding="utf-8", newline="\n")

    print(f"wrote {out} and {tbl}\n" + "\n".join(lines[2:]))
    print("--- tau_int table body ---\n" + "\n".join(trows))


if __name__ == "__main__":
    main()
