"""Generate LaTeX tables + inline-number macros for the Phase IIa short paper.

Writes paper_gauge/tables/*.tex — COMPLETE tabular environments (Phase I
lesson: row-only fragments break TeX alignment lookahead after booktabs
rules) plus numbers.tex, a \\newcommand macro file for every number quoted
inline in the prose. Ground rule 4: no number in the paper is hand-typed;
everything here traces to results/*.json.

Sources:
  results/a4_table.json   (A/B/C accuracy, task A-4)
  results/a5_table.json   (eps_gauge aggregates, task A-5)
  results/a5_curves.json  (accuracy/eps vs n_train, task A-5)
  results/a5eps_*.json    (eps components for the collapse numbers)

Usage:
    python scripts/make_gauge_paper_tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
RESULTS = PROJECT_ROOT / "results"
OUT = PROJECT_ROOT / "paper_gauge" / "tables"

HEADER = "% AUTO-GENERATED by scripts/make_gauge_paper_tables.py -- do not edit\n"
# The three (L, beta) cells where all of A, B, C were trained (task A-4 E1/E3)
SHARED_CELLS = [(8, 1.0), (8, 2.0), (16, 2.0)]


def fmt_pm(mean: float, std: float, digits: int = 3) -> str:
    if 0 < std < 0.5 * 10**-digits:
        # One-significant-figure scientific std (never floor the exponent:
        # 9.2e-5 must print as 9x10^-5, not 10^-5 — a 9x understatement)
        exp = int(np.floor(np.log10(std)))
        mant = int(round(std / 10**exp))
        if mant == 10:
            mant, exp = 1, exp + 1
        std_str = rf"10^{{{exp}}}" if mant == 1 else rf"{mant} \times 10^{{{exp}}}"
        return rf"${mean:.{digits}f} \pm {std_str}$"
    return rf"${mean:.{digits}f} \pm {std:.{digits}f}$"


def fmt_eps(m: dict) -> str:
    if m["mean"] == 0.0 and m["std"] == 0.0:
        return "$0$"
    return fmt_pm(m["mean"], m["std"])


def sci(x: float) -> str:
    """One-significant-figure scientific notation for macro text."""
    exp = int(np.floor(np.log10(abs(x))))
    mant = x / 10**exp
    return rf"{mant:.1f} \times 10^{{{exp}}}"


def load(name: str) -> dict:
    with open(RESULTS / f"{name}.json") as f:
        return json.load(f)


def abc_rows(a4: dict) -> list[dict]:
    rows = [
        r for r in a4["rows"]
        if (r["L"], r["beta"]) in SHARED_CELLS
    ]
    order = {"A": 0, "B": 1, "C": 2}
    return sorted(rows, key=lambda r: (order[r["variant"]], r["L"], r["beta"]))


def write_abc_table(a4: dict) -> None:
    lines = [
        HEADER,
        r"\begin{tabular}{@{}clcrcccc@{}}",
        r"\toprule",
        r"Variant & $L$ & $\beta$ & Params & Action $r$ & $W_{1\times1}$ $r$ "
        r"& $W_{4\times4}$ $r$ & $Q$ acc. \\",
        r"\midrule",
    ]
    prev = None
    for r in abc_rows(a4):
        if prev is not None and r["variant"] != prev:
            lines.append(r"\addlinespace")
        prev = r["variant"]
        lines.append(
            f"{r['variant']} & {r['L']} & {r['beta']:g} & "
            f"{r['n_params'] / 1000:.0f}k & "
            f"{fmt_pm(**r['action_r'])} & "
            f"{fmt_pm(**r['wilson_1x1_r'])} & "
            f"{fmt_pm(**r['wilson_4x4_r'])} & "
            f"{fmt_pm(**r['q_acc'])} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    (OUT / "table_abc_body.tex").write_text("\n".join(lines) + "\n")


def eps_rows(a5: dict) -> list[dict]:
    rows = [
        r for r in a5["rows"]
        if r["experiment"] in ("a4null", "a4C") and (r["L"], r["beta"]) in SHARED_CELLS
    ]
    order = {"A": 0, "B": 1, "C": 2}
    return sorted(rows, key=lambda r: (order[r["variant"]], r["L"], r["beta"]))


def write_eps_table(a5: dict) -> None:
    lines = [
        HEADER,
        r"\begin{tabular}{@{}clccccc@{}}",
        r"\toprule",
        r"Variant & $L$ & $\beta$ & $\epsg^{S}$ & $\epsg^{W_{1\times1}}$ "
        r"& $\epsg^{W_{4\times4}}$ & $\epsg^{Q}$ \\",
        r"\midrule",
    ]
    prev = None
    for r in eps_rows(a5):
        if prev is not None and r["variant"] != prev:
            lines.append(r"\addlinespace")
        prev = r["variant"]
        lines.append(
            f"{r['variant']} & {r['L']} & {r['beta']:g} & "
            f"{fmt_eps(r['eps_energy'])} & "
            f"{fmt_eps(r['eps_wilson_1x1'])} & "
            f"{fmt_eps(r['eps_wilson_4x4'])} & "
            f"{fmt_eps(r['eps_q'])} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    (OUT / "table_eps_body.tex").write_text("\n".join(lines) + "\n")


def collapse_stats(pattern: str) -> tuple[float, float]:
    """Mean action-head config_std over the seeds matching an eps-record glob."""
    vals = [
        json.loads(p.read_text())["metrics"]["energy"]["config_std"]
        for p in sorted(RESULTS.glob(f"a5eps_{pattern}.json"))
    ]
    if not vals:
        raise SystemExit(f"no eps records match {pattern}")
    return float(np.mean(vals)), float(np.std(vals))


def write_numbers(a4: dict, a5: dict, curves: dict) -> None:
    n = {}

    # --- augmentation curves: max |r| over every A/B arm and size ---
    r_keys = ("action_r", "wilson_1x1_r", "wilson_4x4_r", "q_r")
    max_abs_r = max(
        abs(v)
        for label, by_n in curves["arms"].items()
        if label != "C (oracle)"
        for metrics in by_n.values()
        for key in r_keys
        for v in metrics.get(key, [])
    )
    n["AugMaxAbsR"] = f"{np.ceil(max_abs_r * 1000) / 1000:.3f}"  # outward bound

    # --- oracle data efficiency ---
    c_arm = curves["arms"]["C (oracle)"]
    n["COracleActionRAtFifty"] = fmt_pm(
        float(np.mean(c_arm["50"]["action_r"])),
        float(np.std(c_arm["50"]["action_r"])), 2,
    )
    n["COracleActionRAtFourHundred"] = fmt_pm(
        float(np.mean(c_arm["400"]["action_r"])),
        float(np.std(c_arm["400"]["action_r"])), 3,
    )
    n["COracleWFourRFull"] = fmt_pm(
        float(np.mean(c_arm["3200"]["wilson_4x4_r"])),
        float(np.std(c_arm["3200"]["wilson_4x4_r"])), 3,
    )
    # The L=16 protocol cell — the number that matches the receptive-field
    # figure (the curves cell above is L=8)
    for r in a4["rows"]:
        if r["variant"] == "C" and r["L"] == 16 and r["beta"] == 2.0:
            n["COracleWFourRLSixteen"] = fmt_pm(**r["wilson_4x4_r"])

    # --- eps ranges over A/B rows (all experiments, all targets) ---
    # Containment bounds round OUTWARD (floor mins, ceil maxes) so the
    # quoted interval actually contains every value.
    def floor2(x): return f"{np.floor(x * 100) / 100:.2f}"
    def ceil2(x): return f"{np.ceil(x * 100) / 100:.2f}"

    ab_eps = [
        r[f"eps_{t}"]["mean"]
        for r in a5["rows"]
        if r["variant"] in ("A", "B")
        for t in ("energy", "wilson_1x1", "wilson_2x2", "wilson_2x4",
                  "wilson_3x3", "wilson_4x4", "q")
        if r.get(f"eps_{t}") is not None
    ]
    n["EpsABMin"] = floor2(min(ab_eps))
    n["EpsABMax"] = ceil2(max(ab_eps))
    n["NumEpsRows"] = str(len(a5["rows"]))

    # --- beta=1 dip (a4null rows). A's action-head dip is not
    # seed-consistent (0.990 +- 0.033); its cleanest dip is the W1x1 head.
    for r in a5["rows"]:
        if r["experiment"] == "a4null" and r["beta"] == 1.0:
            n[f"EpsBetaOne{r['variant']}"] = fmt_eps(r["eps_energy"])
            if r["variant"] == "A":
                n["EpsBetaOneAWOne"] = fmt_eps(r["eps_wilson_1x1"])

    # --- collapse of the action-head config std (standardized scale) ---
    for tag, pat_small, pat_full in [
        ("AugA", "a5aug_link_nodes_u1_L8_beta2_H64_B3_n50_seed*",
         "a5aug_link_nodes_u1_L8_beta2_H64_B3_n3200_seed*"),
        ("BaseA", "a5base_link_nodes_u1_L8_beta2_H64_B3_n50_seed*",
         "a4null_link_nodes_u1_L8_beta2_H64_B3_seed*"),
    ]:
        m50, _ = collapse_stats(pat_small)
        m32, _ = collapse_stats(pat_full)
        n[f"Collapse{tag}Small"] = f"${sci(m50)}$"
        n[f"Collapse{tag}Full"] = f"${sci(m32)}$"

    # --- escape hatches + parameter-matched arm (accuracy and eps ranges) ---
    hatch = [r for r in a5["rows"] if r["experiment"].startswith("a4hatch")]
    match_ab = [r for r in a5["rows"]
                if r["experiment"] == "a4match" and r["variant"] in ("A", "B")]
    n["HatchMaxAbsActionR"] = f"{max(abs(r['source_action_r']['mean']) for r in hatch):.3f}"
    n["MatchMaxAbsActionR"] = f"{max(abs(r['source_action_r']['mean']) for r in match_ab):.3f}"

    # Across ALL test targets of the hatch runs (not just the action) —
    # the honest companion to the action-only number above.
    r_metric_keys = ("action_r", "q_r", "wilson_1x1_r", "wilson_2x2_r",
                     "wilson_2x4_r", "wilson_3x3_r", "wilson_4x4_r")
    hatch_any = [
        abs(json.loads(p.read_text())["extra"]["source_test_metrics"][k])
        for p in sorted(RESULTS.glob("a5eps_a4hatch*.json"))
        for k in r_metric_keys
        if k in json.loads(p.read_text())["extra"]["source_test_metrics"]
    ]
    n["HatchMaxAbsAnyR"] = f"{max(hatch_any):.3f}"

    def eps_range(rows):
        vals = [
            r[f"eps_{t}"]["mean"] for r in rows
            for t in ("energy", "wilson_1x1", "wilson_2x2", "wilson_2x4",
                      "wilson_3x3", "wilson_4x4", "q")
            if r.get(f"eps_{t}") is not None
        ]
        return floor2(min(vals)), ceil2(max(vals))

    n["EpsHatchMin"], n["EpsHatchMax"] = eps_range(hatch)
    n["EpsMatchABMin"], n["EpsMatchABMax"] = eps_range(match_ab)

    # --- beta=1 accuracy exception (a4 comparison table rows) ---
    for r in a4["rows"]:
        if r["beta"] == 1.0 and r["L"] == 8 and r["variant"] in ("A", "B"):
            n[f"BetaOneActionR{r['variant']}"] = fmt_pm(**r["action_r"])

    # --- source-run bookkeeping ---
    n["KCopies"] = str(a5["rows"][0]["k_copies"])
    n["NumEpsCheckpoints"] = str(sum(r["n_seeds"] for r in a5["rows"]))
    n["NumCCheckpointsExactZero"] = str(
        sum(r["n_seeds"] for r in a5["rows"] if r["variant"] == "C")
    )

    lines = [HEADER,
             "% Macros are BARE MATH (no $..$): always use inside math mode.\n"]
    for key, val in sorted(n.items()):
        lines.append(rf"\newcommand{{\num{key}}}{{{val.replace('$', '')}}}")
    (OUT / "numbers.tex").write_text("\n".join(lines) + "\n")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    a4, a5, curves = load("a4_table"), load("a5_table"), load("a5_curves")
    write_abc_table(a4)
    write_eps_table(a5)
    write_numbers(a4, a5, curves)
    for f in sorted(OUT.glob("*.tex")):
        print(f"wrote {f.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
